name: Filizer
version: 0.0.4-SNAPSHOT
main: com.codeberg.monsieurdoceo.filizer.FilizerPlugin
api-version: 1.21.10
authors: [MonsieurDoceo, TheSayko]
commands:
  check:
    description: "Check and view the contents of a file by a name"
